name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install -r requirements.txt
      - run: npm run installDep
      - run: npm run buildBin
      - run: mkdir release
      - run: cp ./ ./release/
      - run: rm -e ./release/web
      - run: cp ./web/build/ ./release/web/build
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ./release/

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt
      - run: npm run installDep
      - run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "./web/build"
          exclude_assets: ".github,exclude-file1,exclude-file2"

          publish_branch: master
