name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Building
        run: |
          cd src
          pip install -r requirements.txt
          npm run installDep
          npm run build
          cd ..
      - name: Creating release
        run: |
          mkdir release
          cp -r ./src/. ./release/
          rm -r ./release/web
          mkdir release/web
          cp -r ./src/web/build/ ./release/web/build
          zip -r release.zip ./release/*
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Development Build"
          files: ./release.zip
